### ISSUE TITLE
Observability: OpenTelemetry support

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#171]
Kusk-gateway should be able to add OT-headers and expose collected trace data!?

**Comment by Tarick** [comment]
Yes, it should be able to augment already initiated span or initiate it randomly  [Envoy Tracing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing), that can be configurable.

**Comment by olensmar** [comment]
thanks @Tarick - @kdhamric please add anything there that might be relevant/related to OT...

**Comment by aabedraba** [comment]
We have this already in the doc, please let me know if you'd need better docs/support for this one. Closing for now. 

https://docs.kusk.io/guides/observability
