### ISSUE TITLE
High Availability: Envoy Healthchecks

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#183]
**Describe the enhancement you'd like to see**

Envoy proxy pods should have the healthcheck, that will return true only when Envoy gets all the configuration from the control plane. In the situations when the Envoy Proxy service is updated or pods are being migrated between nodes, we can receive the traffic interruptions when the pod hasn't got the configuration yet.

**Comment by aabedraba** [comment]
Dropping for now, perhaps we can take this further on.
