### ISSUE TITLE
Logs: do not log whole API objects

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gateway#185]
**Describe the bug**
https://github.com/kubeshop/kusk-gateway/blob/main/controllers/config_manager.go#L88-L106
We shouldn't log whole API objects, especially on Info level.

**Comment by Tarick** [comment]
Would be great to introduce the configurable logging level and log.DEBUG statement.

**Comment by kylehodgetts** [comment]
it would also be nice that if we do need to print the whole object - it's formatted so it's easy to read
Perhaps we can override the `String()` method to achieve this?
