### ISSUE TITLE
Protect API gateway and underlying services from malicious / malformed JSON

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gateway#20]
It could make sense to incorporate some level of protection into kusk-gateway, i.e. something like [this](https://github.com/ankur-anand/gojtp).

Other security features could be: SYN flood protection, max payload size, countermeasures for slowloris attack, etc.
This would make kusk-gateway more appealing for hosting production workloads.

**Comment by aabedraba** [comment]
this is solved with 

```
x-kusk:
  validation: 
	request: 
		enabled: true
```
