### ISSUE TITLE
Add pane listing static routes, with details panel

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#229]
we should have a pane listing static routes configured kusk-gateway - similar to the pane we have for listing APIs. The corresponding API operations need to be defined - i.g. getStaticRoutes and getStaticRouteDetails

Not sure what metadata we could show in the list and details panel

**Comment by jasmingacic** [comment]
I will move this to the REST API https://github.com/kubeshop/kuskgateway-api-server/issues/10
