### ISSUE TITLE
Visualize kusk-extensions in Swagger-UI interface

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#230]
I would like to see the configuration provided by kusk-extensions in the Swagger-ui component:
- if an operation is enabled/disabled
- If mocking is enabled/disabled
- Settings for timeouts
- ?

If this can't be "overlayed" into the existing swagger-ui component perhaps we need a separate tab that shows a list of all operations with corresponding settings !?

**Comment by jasmingacic** [comment]
I believe this one is done. 
@topliceanurazvan can you close it if you agree
