### ISSUE TITLE
Usage telemetry

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#254]
Before releasing kusk we should have some sort of usage data collection.

Something we could look at is:
https://segment.com/docs/connections/sources/catalog/libraries/server/go/

**Comment by olensmar** [comment]
Sounds good @jasmingacic - let's start with collecting telemetry on:
- heartbeat / installations
- nr of CRDs deployed per type (i.e. each

Need to make sure this is optional and can be turned off - perhaps via #105

**Comment by jasmingacic** [comment]
Done for the operator. 
Needs to be added to the CLI too
