### ISSUE TITLE
rename kgw tool to kusk

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#280]
with corresponding README updates - once merged we can rename the repo (after existing kusk repo has been renamed to kusk-gen)

**Comment by jasmingacic** [comment]
kgw is now -> kusk and kusk -> kusk-gen
@olensmar whom should we notify about this change so the website can be updated accordingly?

**Comment by olensmar** [comment]
@jasmingacic please let Tina know to start with - thanks!
