### ISSUE TITLE
extend /services to return all available services

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#282]
to be able to show the user a list of available services when they use #248 - perhaps by adding a filter parameter?

When returning all services each ServiceItem needs to contain 
- name
- namespace
- ports/port-ranges

The user will be able to select one of the returned services and provide a specific port if needed (i.e. if multiple ports are available)

**Comment by topliceanurazvan** [comment]
OpenAPI Spec Update PR - https://github.com/kubeshop/kuskgateway-api-server/pull/24
