### ISSUE TITLE
Extend Deployment wizard with configuration options

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#283]
When deploying an API through #248 I would like to be able to specify a number of root-level extensions:
- if mocking should be enabled; checkbox (would remove the requirement to select an upstream service)
- if validation should be enabled: checkbox - requires upstream service
- path prefix: optional string
- qos properties; retries, request_timeout, idle_timeout - corresponding number input fields (optional)
- if cors should be enabled; checkbox with corresponding configuration properties (origins, methods, headers,etc)

see https://kubeshop.github.io/kusk-gateway/extension/

If the provided OpenAPI definition already contains any of these properties then the form should be prefilled with those values

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kusk-gateway-dashboard/pull/38
