### ISSUE TITLE
dedicated API operations for retrieving CRDs/OpenAPI defs

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#286]
As a consumer of the kusk-gateway API I would like to have dedicated operations for retrieving CRDs and OpenAPI definitions:

`/apis/{namespace}/{name}/definition` to get the post-processed openapi definition for the specified API (the pre-processed can be extracted from the CRD)

`/apis|staticroutes|envoyfleets/{namespace}/{name}/crd` to get the crd for the corresponding object

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kuskgateway-api-server/pull/23
