### ISSUE TITLE
Service Reconciler doesn't add x-kusk path option if missing

### ISSUE THREAD

**Issue by kylehodgetts** [kubeshop/kusk-gateway#290]
**Describe the bug**
When the service reconciler detects a service definition with the following annotation `kusk-gateway/openapi-url"` it creates an `API` taken from the URL of the annotation and adds the x-kusk upstream service option taking this info from the service manifest itself. It then applies the API.

The problem arises if the openapi spec doesn't contain the x-kusk path option. When the service reconciler tries to apply the API, it fails the API validating webhook with the following message
```
admission webhook \"vapi.kb.io\" denied the request: spec: should be a valid OpenAPI spec, no paths found.
```

The path is required so Envoy knows at which path the service should be reachable

**Expected behavior**
 The service reconciler should add some path options so the new API resource passes the validating webhook.

This then brings up the following problem: what if the path the reconciler chooses is already taken by another service.
This needs a wider discussion.

**Comment by olensmar** [comment]
thanks @kylehodgetts - i didn't realise the path was required when specifying this functionality... would a possible solution be:
- look for a `kusk-gateway/api-path` annotation containing the path
- if not available use `/` as the path?

cc @jasmingacic
