### ISSUE TITLE
API Mocking returns different Content-Type each execution

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#297]
**Describe the bug**
Running the mocking on an API (json, xml and text mocking) sometimes returns xml and sometimes returns text.  

**To Reproduce**
Apply the following manifest with 

```sh
kgw api generate -i https://pastebin.com/raw/avYFtZpX | k apply -f -
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/163005242-d9ef39c1-6a85-4fd7-9bc2-89141ffd561f.png)

**Desktop (please complete the following information):**
 - Kubernetes version
 - Kube Gateway Version

 
**Additional context**

**Comment by jasmingacic** [comment]
Behavior is as expected of accept header is passed the response will be of the corresponding content-type see below:
```
# curl -v -H 'accept: application/xml'  localhost:8011/todos
*   Trying ::1:8011...
* TCP_NODELAY set
* Connected to localhost (::1) port 8011 (#0)
> GET /todos HTTP/1.1
> Host: localhost:8011
> User-Agent: curl/7.68.0
> accept: application/xml
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/xml
< x-kusk-mocked: true
< date: Wed, 20 Apr 2022 12:09:07 GMT
< content-length: 117
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host localhost left intact
<doc><completed>true</completed><order>13</order><title>Mocked XML title</title><url>http://mockedURL.com</url></doc>
```

If accept is not passed or you use */* then it will return each time a different content-type. 
I'm closing this as an non-issue
