### ISSUE TITLE
Add "Mock API" action to dashboard

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#299]
As a user i would like to mock an API defined in my OpenAPI definition - I know I can do this by going through the existing deployment wizard and/or by adding the corresponding x-kusk extension, but it would be nice to have a "shortcut" action for this which only prompts me for the OpenAPI definition and nothing else.

The implementation would
- add the x-kusk.mocking.enabled extension at the root level
- generate a unique API name from the name of the API in the definition - prefixed with "mock"
- deploy the API in the kusk namespace

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kusk-gateway-dashboard/pull/40
