### ISSUE TITLE
Add "Publish" button to deployment wizard

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#304]
To make it easy for users to bypass non-mandatory configuration options in the deployment wizard; 

- If the user selects "Enable mocking of this API" - immediately enable "Publish" button, otherwise the user has to provide upstream/redirect information for the Publish button to be enabled

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kusk-gateway-dashboard/pull/41
