### ISSUE TITLE
ToC operation links not working

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#312]
The links for the /staticroutes operations in the post-processed definitions ToC don't work - i.e. clicking on them does nothing

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1917063/164202477-1eae4390-cc5f-47f7-8e04-08e845eac353.png">

**Comment by topliceanurazvan** [comment]
Commit - https://github.com/kubeshop/kusk-gateway-dashboard/commit/87f38d63b319324b0066d1dfc90181234bab36d6
