### ISSUE TITLE
Change naming of API definition tabs in UI

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#313]
To make it more clear I suggest to rename the API spec tabs as follows:
- "Raw API Spec" -> "API Definition"
- "Kusk Extensions" -> same name, move to second place
- "Post-processed API Spec" -> "Public API Definition".

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kusk-gateway-dashboard/pull/52
