### ISSUE TITLE
Make it possible to see the YAML of an API definition

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#314]
As a dev I want to see the actual YAML of the deployed or published API definition

**Comment by mortada-codes** [comment]
@olensmar  do you mean something else other than the CRD?

**Comment by olensmar** [comment]
yes - i meant just the openapi definition - not the CRD that contains it - although this is perhaps more relevant for the public/post-processed definition

**Comment by mortada-codes** [comment]
Thank you!

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway/projects/5#card-81136493

**Comment by jasmingacic** [comment]
@mortada-codes do you need more information about this?

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/120
