### ISSUE TITLE
Use default-marked envoy fleet

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#328]
**Describe the enhancement you'd like to see**
Right now, when deploying an API, given that we have two Envoy Fleets, one for dashboard and one for the public gateway, we need to add the fleet we want to deploy the API to in the manifest.

Could we add a way to have a default EnvoyFleet to deploy to so we don't need to define that every time in every manifest?

**Comment by aabedraba** [comment]
Suggested solution by @kylehodgetts: "introduce an annotation on Envoyfleets to mark it as default and then if no envoy fleet is specified, make it use the one marked default"

**Comment by olensmar** [comment]
Would it be feasible to use any single existing EnvoyFleet as the default? I.e. if only one EnvoyFleet exists it is implicitly the default - and the annotation only comes into play if there are several fleets? 

(In this case if there are several fleets and none has the annotation we would have to use some heuristic to determine which should be used as default.)

**Comment by aabedraba** [comment]
> if only one EnvoyFleet exists it is implicitly the default 

@olensmar it currently works this way. 

But since the new install command adds two envoy fleets by design, that's why we start needing a default envoy fleet concept

**Comment by povilasv** [comment]
I would consider just adding a field instead of annotation, as it's really an anti-pattern.

Example in Kubernetes ingress class moved from annotation to field:

>Before the IngressClass resource was added in Kubernetes 1.18, a similar concept of Ingress class was often specified with a kubernetes.io/ingress.class annotation on the Ingress. Although this annotation was never formally defined, it was widely supported by Ingress controllers, and should now be considered formally deprecated.

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

**Comment by olensmar** [comment]
@povilasv you mean we add a property to the EnvoyFleet schema that says if a specific fleet is the default one?

**Comment by crjones** [comment]
From refinement:

When no fleet is specified:
Prompt for selection of fleet, and provide help on how to specify a fleet in the spec or command line flag.

**Comment by jasmingacic** [comment]
From operator perspective:
Envoyfleet scope:
1. Extend envoyfleet with flag `default` as a **property** per comment https://github.com/kubeshop/kusk-gateway/issues/328#issuecomment-1116953231
2. There can only be a single default fleet (per namespace?) - done in validating webhook 

API scope:
1.  Avoid mutating webhook which is slapping default fleet to the API

**Comment by crjones** [comment]
As discussed this morning. Defaulting the envoy fleet to `kusk-gateway-envoy-fleet` and still allowing override from the command option.

@jasmingacic has a PR #582 that should resolve this issue.
