### ISSUE TITLE
TLS: with static certificates

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gateway#33]
Introduce a new CRD for configuring TLS.

Based on the context and TLS workflows, people will be creating the certificates secrets manually and at the same time LetsEncrypt (CertManager) certificates will be updated dynamically, so we need to send to Envoy information on new certs when this happens. 

Since TLS is mapped to the Listener config and EnvoyFleet doesn't manage listener config, but EnvoyConfigManager does when Envoy is ready, we need to send this as part of Envoy application configuration - not as part of Fleet configuration.

Fields for CRD
- Secret ref containing certs
- Cipher suites order string (users will likely exclude or include ciphes depending on their usecases.)

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto has some of those, 

I think for the first iteration we need only the secret ref and ciphers order (which again has a sane default - we can make it optional for the user, but allow to configure).

Then manager has to pull this on startup/creation and update and send this to Envoy with listener configuration.

The Envoy config manager sends the whole configuration in one go (we don't do delta configuration currently), it must be a part of main configuration routine in https://github.com/kubeshop/kusk-gateway/blob/main/controllers/config_manager.go#L56

**Comment by Tarick** [comment]
As per conversation we agreed that this should be part of EnvoyFleet CRD for the best UX.
