### ISSUE TITLE
[Bug]: `kusk api generate` does not add an Envoy Fleet

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#332]
### What happened?

`kusk api generate` does not add an Envoy Fleet to the generated CRD, so it never works. 

Could we: 
1- Add a default Envoy fleet for now? hacky hard-coding... 
or 
2- Pass an Envoy fleet name to the command

### Version

1.0.0 (Default)

**Comment by olensmar** [comment]
Alternatively we resolve #328 - which would remove the requirement for an Envoy Fleet to be specified?

**Comment by aabedraba** [comment]
@olensmar correct - just not sure if we could fit it in the current sprint as the of the code that handles that is not owned by the current team

**Comment by olensmar** [comment]
thanks @aabedraba - whichever is easiest - we just can't release 1.0 with a cli that generates unusable output
