### ISSUE TITLE
Add setting to specify BE API endpoint

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#337]
As a user I would like to configure the dashboard to use a different API endpoint then the default one (<dashboard host:port>/api) 

Suggest to have a setting for this in the dashboard that would override the default endpoint and store it in local storage (similar to how the testkube dashboard works)

**Comment by topliceanurazvan** [comment]
PR - https://github.com/kubeshop/kusk-gateway-dashboard/pull/74
