### ISSUE TITLE
Return value property of first example when mocking a response that has multiple examples

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#341]
see https://swagger.io/docs/specification/adding-examples/ - when a response has multiple examples defined we should return the content of the "value" property of the first example as a mock response

**Comment by povilasv** [comment]
There is an issue that map don't really have order in go. The underlying library that parses Open API specs use maps. 
So this issue is not easily fixable :/

Reference: https://github.com/getkin/kin-openapi/issues/47

**Comment by olensmar** [comment]
valid point - and maps in yaml/json aren't ordered anyway - i'm fine with just returning whatever example happens to be first in the internal map, if users want more control over which response to return we could add additional configuration properties for this

**Comment by povilasv** [comment]
I believe this is what is happening right now, as in my unit tests with multiple examples we return the first mocked example.

Golang maps actually make it so that once you iterate the map it will return a random element -> https://stackoverflow.com/questions/55925822/why-are-iterations-over-maps-random

I'll do more e2e tests to validate this behavior

**Comment by povilasv** [comment]
I've tested current version with:
```
curl -X GET /testing/mocked/multiple/1
```

returns:

```
{"completed":true,"order":12,"title":"Mocked title #1","url":"http://mockedURL.com"}%
```

For the following config:
```
# Mocked
      # In "responses" there are multiple examples
      /mocked/multiple/{id}:
        # Enable mocking with x-kusk
        x-kusk:
          mocking:
            enabled: true
        get:
          responses:
            '200':
              description: 'Mocked ToDos'
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      title:
                        type: string
                        description: Description of what to do
                      completed:
                        type: boolean
                      order:
                        type: integer
                        format: int32
                      url:
                        type: string
                    required:
                      - title
                      - completed
                      - order
                      - url
                  # This example is the must for the response body mocking
                  examples:
                    first:
                      title: "Mocked title #1"
                      completed: true
                      order: 12
                      url: "http://mockedURL.com"
                    second:
                      title: "Mocked title #2"
                      completed: true
                      order: 13
                      url: "http://mockedURL.com"

```

**Comment by povilasv** [comment]
@olensmar do you have any specific example for this when it didn't work?

Cause my unit tests and local testing shows that mutiple example case works :)

**Comment by olensmar** [comment]
@povilasv the above yaml is incorrect - per the [OpenAPI Examples spec](https://spec.openapis.org/oas/v3.1.0#example-object) - the actual example should be in a child `value` property of the example keys, i.e.

```yaml
...
                  # This example is the must for the response body mocking
                  examples:
                    first:
                      value:
                        title: "Mocked title #1"
                        completed: true
                        order: 12
                        url: "http://mockedURL.com"
                    second:
                      value:
                        title: "Mocked title #2"
                        completed: true
                        order: 13
                        url: "http://mockedURL.com"

```

 
see https://swagger.io/docs/specification/adding-examples/ for another example
