### ISSUE TITLE
Allow users to cache certain requests in envoy

### ISSUE THREAD

**Issue by povilasv** [kubeshop/kusk-gateway#347]
might be some `x-kusk: cache` extension. Also we need to think about cache eviction policies and stuff like that.

Some background information:
https://twitter.com/copyconstruct/status/1288996754814193664
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache
https://docs.google.com/document/d/1WPuim_GzhfdsnIj_tf-fIeutK0jO4aVQfVrLJFoLN3g/view#heading=h.wjxw6fq7wefi

**Comment by crjones** [comment]
@povilasv How is this going? Any progress on the implementation?

**Comment by jasmingacic** [comment]
@povilasv Can you add some update here?
