### ISSUE TITLE
API Publish wizard EnvoyFleet step

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/kusk-gateway#353]
Add an additional step where the user should be able to select the EnvoyFleet.

The step should contain ( similar to selecting cluster service on `Target` step ) :
- Dropdown for selecting the EnvoyFleet
- Input for name
- Input for namespace

**Comment by olensmar** [comment]
I think the drop-down is enough!? why would we need name/namespace fields?

**Comment by olensmar** [comment]
this is required to circumvent the issue that is described in #389 which will happen even if mocking is not selected and there is more than one EnvoyFleet

**Comment by mortada-codes** [comment]
related issue: #389
