### ISSUE TITLE
Create "Automated Deployment" section in documentation

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#364]
Since this is one of the main selling points of Kusk Gateway I suggest we have dedicated guides that cover the (mostly automated) deployment workflow achievable with Kusk Gateway:
- Using Annotations
- Using ArgoCD
- Using GitHub Actions 
- Using just the CLI and kubectl 
- ?

**Comment by jasmingacic** [comment]
SVC annotations have been removed. So this is no longer relevant
