### ISSUE TITLE
K8s Gateway API 

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#372]
https://gateway-api.sigs.k8s.io/

Already supports several [implementations](https://gateway-api.sigs.k8s.io/implementations/#implementations) and we should be able to ride on its back. 
An example of how it works https://github.com/kubernetes-sigs/gateway-api/blob/master/examples/v1alpha2/basic-http.yaml

If our operator was to configure something similar based on API object we should be golden. I.E. based on x-kusk extensions we should be able to extract [HTTPRoute](https://gateway-api.sigs.k8s.io/v1alpha2/api-types/httproute/)

**Comment by jasmingacic** [comment]
This approach would supersede #370 and #371

**Comment by jasmingacic** [comment]
The major drawback is that there are quite a few [GEPs](https://gateway-api.sigs.k8s.io/contributing/gep/#gateway-enhancement-proposal-gep) we could potentially contribute upstream to speed up the process. It gives us several benefits 1. gives Kubeshop street creds and 2. speeds up our delivery on kusk-gateway

**Comment by aabedraba** [comment]
We'll pick this up later on when Gateway API is more stable and it makes sense for us to use it. Perhaps we could even target https://github.com/envoyproxy/gateway instead.
