### ISSUE TITLE
Import openapi spec from url 

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#381]
currently, when a user wants to publish a new api, user has to paste the openapi spec  yaml/json to the form.
we can add way to import the openapi spec from url 

** current form ** 
<img width="977" alt="Screen Shot 2022-05-09 at 1 31 41 PM" src="https://user-images.githubusercontent.com/20525304/167401878-cffa627a-f0d4-4048-8fed-77d376a2932e.png">

**Comment by olensmar** [comment]
great idea! - we discussed this initially but were worried that there could be CORS issues when trying to request an openapi definition from an arbitrary URL - but that might be a corner case!?
