### ISSUE TITLE
Admission webhook throws error when mocking

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#389]
I'm trying to mock the API at https://api.apis.guru/v2/specs/abstractapi.com/geolocation/1.0.0/openapi.yaml through the dashboard wizard - when deploying I get the following error: 

![image](https://user-images.githubusercontent.com/1917063/167710448-431f4458-c530-4b81-8602-75be681befff.png)

There are two fleets in my cluster - but it seems to me that neither should be needed when mocking!? 

Also - I can't seem to be able to specify a fleet in the wizard - should I open a separate issue for that?

**Comment by jasmingacic** [comment]
Related to #328 
Let's discuss this a bit more to crystalize potential solution. 
My suggestions:

1. I would go with the option that if `fleet` property is provided in the API that operator should create one with the provided name.  - even if this looks like a convenient option somehow when stuff happens automagically I'm little skittish 
2. Another option would be to simply mark `fleet` property as required and when provided with non existent fleet return error to the user. - somehow this feels less invasive.

**Comment by jasmingacic** [comment]
Also related to #255
