### ISSUE TITLE
Modify /apis post request body. add fleet info

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#391]
add fleet info to the /apis post request based on https://github.com/kubeshop/kuskgateway-api-server/pull/41

fix: https://github.com/kubeshop/kusk-gateway/issues/389 & 
https://github.com/kubeshop/kusk-gateway/issues/353

**Comment by jasmingacic** [comment]
@mortada-codes #389 needs more work around it. Can you take it away so it doesn't get close one you finish this
