### ISSUE TITLE
Add progress bar to `kusk install`

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#394]
When running the `kusk install` I wasn't sure if my terminal hanged or the process failed as it looked like the following 

![image](https://user-images.githubusercontent.com/27779735/168002210-56078c5b-6b82-475a-b641-ceed0ba259c0.png)

Could we add a spinning wheel? 🙃

**Comment by kylehodgetts** [comment]
Could use something like this https://github.com/janeczku/go-spinner

**Comment by gunishmatta** [comment]
I would like to work on this if no one is working right now @kylehodgetts

**Comment by kylehodgetts** [comment]
@gunishmatta by all means! We would be happy to receive your contribution!

**Comment by aabedraba** [comment]
@gunishmatta echoing Kyle, please feel free to do it!! Thanks a lot for the interest :) 

As a note, the file that is responsible for the command is https://github.com/kubeshop/kusk-gateway/blob/main/cmd/kusk/cmd/install.go , you'd start looking there if you want to add a spinner :) 

Please let us know if you decide to start on it!

**Comment by gunishmatta** [comment]
I am starting on it.

@aabedraba

**Comment by aabedraba** [comment]
@gunishmatta were you able to give it.. a spin? :) 

Please let me know if you'd like me to help you get this done!
