### ISSUE TITLE
Mocking Service based on API spec, enabled explicitly in API CRD, mock responsess provided from OpenAPI examples

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gateway#41]

**Comment by Tarick** [comment]
Preliminary design considerations:
1. Mocking service as a sidecar to Envoy Proxy.
2. On specifying enabled mocking per path/method - setup Envoy routing for this path/method to the sidecar and update sidecar configuration for this path/method. Update configuration using GRPC transport with snapshots similarly as Envoy's XDS is implemented.
3. Mocking service as an HTTP server with only one route /.
4. Mocking service identifies the mocking configuration for that path/method using some additional header.
5. Mocking service generates mocking configuration using the examples section OR similarly as https://github.com/muonsoft/openapi-mock does. Initial implementation should use the examples from OpenAPI spec.
