### ISSUE TITLE
Kusk CLI "version"

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#415]
We don't have version command to do any check or validations of the CLI version

**Comment by crjones** [comment]
When we add this, can we add it to the telemetry data?

**Comment by jasmingacic** [comment]
Yes we should. Can anyone add it in https://github.com/kubeshop/kusk-gateway/pull/413?

**Comment by mbana** [comment]
`kusk` now reports version information:

```sh
./kusk version; ./kusk --version; ./kusk -v             
kusk version 1.0.5-rc1
https://github.com/kubeshop/kusk/releases/tag/v1.0.5-rc1
kusk version 1.0.5-rc1
https://github.com/kubeshop/kusk/releases/tag/v1.0.5-rc1
kusk version 1.0.5-rc1
https://github.com/kubeshop/kusk/releases/tag/v1.0.5-rc1
```

*NB:* The version is `v1.0.5-rc1` not `v1.0.5`.
