### ISSUE TITLE
add mock command to cli

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk-gateway#428]
To make it super-easy to mock an OpenAPI definition I would like to be able to do the following:

`kusk mock <path/url to OpenAPI definition> [-prefix <prefix>]`

which would add the mock extension at the root level and deploy the API under the specified prefix. A couple of caveats:

- if no operations have any examples the command should fail (until we implement mocking from schema) 
- if only some operations have examples then the command should succeed and print a list of operation that are mocked (i.e. that have examples)
- if all operations have examples the the command should succeed and print "API mocked successfully"

The output should also include at which host/path the mocked API is reachable.

For example

`kusk mock https://petstore3.swagger.io/api/v3/openapi.json -prefix /petstore `

would mock the swagger petstore API under the /petstore prefix

**Comment by aabedraba** [comment]
We should probably share the same logic with the dashboard too!

**Comment by jasmingacic** [comment]
already implemented in the CLI

**Comment by crjones** [comment]
Is this already implemented? The current command mocks locally, but this issue suggests adding mocking extensions and deploying to the cluster.

**Comment by jasmingacic** [comment]
since that's the case i will reopen it

**Comment by aabedraba** [comment]
The suggested solution does not allow us to have the OpenAPI as source of truth as there are mutations applied outside of the current OpenAPI workflow...
Perhaps we shouldn't pursue this idea, and think more of how we can get users to use the OpenAPI more 🤔 
@crjones @jasmingacic

**Comment by jasmingacic** [comment]
We can make it so that auto mocking which is running locally now can be switched from local to cluster context and we allow users to play with it. The only drawback here is that the operator can't mock from schema at the moment only where examples are available.

Let's talk about this in our planning sessions

**Comment by crjones** [comment]
> The suggested solution does not allow us to have the OpenAPI as source of truth as there are mutations applied outside of the current OpenAPI workflow...
> Perhaps we shouldn't pursue this idea, and think more of how we can get users to use the OpenAPI more 🤔 
> @crjones @jasmingacic  

Agree, just didn't want to mark it closed as already implemented.

**Comment by aabedraba** [comment]
Work to be tracked here https://github.com/kubeshop/kusk-gateway/issues/723
