### ISSUE TITLE
Support HTTP `options`

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#433]
As a user I want to see the HTTP OPTIONS that the API has

**Comment by aabedraba** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by jasmingacic** [comment]
Can't reproduce

**Comment by aabedraba** [comment]
@povilasv can you tell me why I'm getting this error, please? 🙏🏽

I'm making the following request and: 

```sh
$ curl -X OPTIONS localhost:8081 -v
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> OPTIONS / HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Tue, 02 Aug 2022 11:24:01 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host localhost left intact
```

Same with httpie

```sh
$ http options :8081 -v
OPTIONS / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8081
User-Agent: HTTPie/3.2.1



HTTP/1.1 404 Not Found
content-length: 0
date: Tue, 02 Aug 2022 11:24:58 GMT
server: envoy
```

**Comment by aabedraba** [comment]
After we talked, we should implement this https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by olensmar** [comment]
@aabedraba how is this different from the x-kusk cors extension?

**Comment by aabedraba** [comment]
@olensmar the problem that I found is that the OPTIONS request returns a 404 as you can see from my last comment
https://github.com/kubeshop/kusk-gateway/issues/433#issuecomment-1202356668

so I thought we didn’t implement this, but as you correctly noted we have that through the CORS extension

we just need to fix the bug(? question mark bc I don't know if this feature ever worked)

**Comment by aabedraba** [comment]
This works as expected.
