### ISSUE TITLE
Option to disable cluster telemetry after installed

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#449]
Should be possible to disable it pre-installation and post-installation.

**Comment by crjones** [comment]
As a user I want to be able to toggle the collection of analytics data from the command line post install so I can control what data is collected from my installation.

You might also include issue #537 to turn off cluster and dashboard analytics at the same time.

**Comment by crjones** [comment]
What would be the recommended command to toggle this setting. Do we have a pattern for toggling setting yet?
