### ISSUE TITLE
services endpoint returns duplicate values

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#453]
**Describe the bug**
when calling /services should return a distinct array of services  but it returns a duplicate items

**To Reproduce**
1. call `/services`
2. See error

**Expected behavior**
a distinct array of services

**Screenshots**
<img width="1350" alt="Screen Shot 2022-06-02 at 12 52 35 PM" src="https://user-images.githubusercontent.com/20525304/171614277-c155fd61-94e2-4afc-82af-3532cab31cc2.png">

**Comment by kylehodgetts** [comment]
Already completed by @jasmingacic
