### ISSUE TITLE
Local mocking from the CLI

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#491]
As an API developer, I want to spin up a mock API server on the CLI using an OpenAPI spec.

- [x] Parse OpenAPI Spec
- [x] Initialise mock server with routes and responses.
- [x] If a route+method has example responses, use them, else generate content that matches the content schema
- [x] React to changes to the input file, re-parsing and reinitialising the mocking server

Cosmetic:

- [x] stream access logs from mocked server to stdout

**Comment by fivenp** [comment]
From a ux perspective this would be an amazing flow for the user

![image](https://user-images.githubusercontent.com/132332/176143165-429d4a21-c2b8-45dc-91d7-b5554e641495.png)

**Comment by crjones** [comment]
Love these mocks. I came to this issue to do just this and you already did it and WAY better!

**Comment by aabedraba** [comment]
Basic functionality is working, and ready for demo. 
Using https://github.com/muonsoft/openapi-mock

**Comment by aabedraba** [comment]
Team Sync: issue missing on relative and absolute paths, to be worked on 

Next will be documentation
