### ISSUE TITLE
Add a file watcher to Kusk CLI 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#513]
**Describe the enhancement you'd like to see**
When I update the `openapi.yaml` file, I need to run the following command for each update 

```sh
kusk api generate --envoyfleet.name kusk-gateway-envoy-fleet -i openapi.yaml | kubectl apply -f -
```

I'd love to have a watch feature that checks for changes and tries to automatically add them to the cluster. The following could be an example

```sh
kusk api generate --envoyfleet.name kusk-gateway-envoy-fleet -i openapi.yaml --watch 
```
 - `--watch` option would watch the file

**Comment by crjones** [comment]
@kylehodgetts could we use something similar to what was done for mocking from the cli to watch and reapply?

**Comment by aabedraba** [comment]
Done with `kusk deplo`
