### ISSUE TITLE
When using the `api generate` command, apply directly to the cluster

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#514]
**Describe the enhancement you'd like to see**
Currently the flow is to run the command and pipe it to `kubectl`

```sh
kusk api generate --envoyfleet.name kusk-gateway-envoy-fleet -i openapi.yaml | kubectl apply -f -
```

Would be great if we could add a `--apply` flag to it and it applies it directly to the cluster

Another alternative could be applying by default, and in case the user needs the CRD they could take it by `--generate-crd-only`? 🤔

**Comment by kylehodgetts** [comment]
Superceded by kusk deploy
