### ISSUE TITLE
Re-work Kusk Dashboard to new design

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#522]
Designs from Figma: https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=74%3A1672

Still to be confirmed tomorrow

**Comment by aabedraba** [comment]
In progress

**Comment by crjones** [comment]
Added this to the epics. We have split this into multiple issues. #557 #554 #553

**Comment by jasmingacic** [comment]
@donnalux @mortada-codes I believe this has been completed. 
Can one of you close this issue if that's the case?
