### ISSUE TITLE
Merge `kusk` CLI repository into kusk-gateway

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#529]
**Is your feature request related to a problem? Please describe.**
To clear user confusion and better promote kusk, could we merge the kusk respository https://github.com/kubeshop/kusk with this repository and perhaps even change the naming of this one to "kusk"?

**Comment by jasmingacic** [comment]
Tasks:

Website, 
Website links,
Databox, 
Metric Dashboards,
