### ISSUE TITLE
Centralize analytics and make it predictable across dashboard, cli and cluster

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#537]
@crjones to create a matrix of analytics options, etc

**Comment by crjones** [comment]
GIVEN Analytics are OFF in the CLI
WHEN Installing to a cluster
THEN Turn OFF analytics on the gateway and dashboard

GIVEN Analytics are ON in the CLI
WHEN Installing to a cluster
THEN Turn ON analytics on the gateway and dashboard

GIVEN Analytics are OFF in the CLI
WHEN Installing to a cluster
THEN Turn OFF analytics on the gateway and dashboard

**Comment by aabedraba** [comment]
Adding one more case: 

GIVEN Analytics are ON in the CLI AND Analytics are ON in the cluster
WHEN disabling analytics
THEN Turn OFF analytics on the gateway, dashboard and CLI

**Comment by jasmingacic** [comment]
What's the status on this?

**Comment by jasmingacic** [comment]
I believe this has been implemented
