### ISSUE TITLE
`mock` command fails to start

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#552]
Running `kusk mock` for the first time got me this error message 

```sh
kusk mock -i openapi.yaml
🎉 successfully parsed OpenAPI spec
☀️ initializing mocking server
⨯ unable to create mocking server: Error response from daemon: No such image: muonsoft/openapi-mock:v0.3.1 💔
```

**Comment by jasmingacic** [comment]
https://github.com/kubeshop/kusk/blob/main/internal/mocking/server/server.go#L46

Reader closed before the image was downloaded.  Just add something similar to this:
```
defer reader.Close()
io.Copy(os.Stdout, reader) // this will print out raw output 
```

**Comment by jasmingacic** [comment]
Another issue I found if you are running automocking and you already have a cluster with service listening at port 8080 you can't get to localhost:8080
![image](https://user-images.githubusercontent.com/8327751/179942698-7696124c-1c30-466d-af56-d7f986fa3c53.png)

Maybe it would be good to be able to configure the port

**Comment by aabedraba** [comment]
https://github.com/kubeshop/testkube/pull/1773
