### ISSUE TITLE
Error message remains when another namespace is selected

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#583]
1. Click Add a new API button
2. Use name of an exising API
3. Select ToDo App Template or Blank canvas

<img width="395" alt="image" src="https://user-images.githubusercontent.com/102221761/182913924-e0113243-739c-44a9-8e74-9afdad54e5f3.png">

Error appears before namespace has been selected.

4. Selecting or changing namespace does not clear error

<img width="399" alt="image" src="https://user-images.githubusercontent.com/102221761/182914397-ffd6dbd9-8269-4429-b586-7529540b778a.png">

**Comment by mortada-codes** [comment]
solved https://github.com/kubeshop/kusk-gateway-dashboard/pull/176
