### ISSUE TITLE
Simplify brew install command

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#584]
Simplify brew install commands from:

```
brew tap kubeshop/kusk
brew install kusk
```

to:

```
brew install kusk
```

**Comment by aabedraba** [comment]
We should work with Testkube to ask them about the process of getting Kusk added to main brew tap. 
Perhaps @jmelnych can help?

**Comment by crjones** [comment]
Would love to simplify this ...

![Image](https://user-images.githubusercontent.com/61113/190002922-1eae1356-9bb8-4444-a342-a59593074944.png)

**Comment by aabedraba** [comment]
Official brew core is slow on releases and doesn't offer metrics. 
Not a priority at the moment.
(see Confluence page on Telemetry)
