### ISSUE TITLE
When using kusk upgrade command, i cannot know what is the version from the message

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#596]
**Describe the enhancement you'd like to see**
Add the upgraded version to the kusk cli upgrade message 

**Additional context**
<img width="578" alt="Screen Shot 2022-08-09 at 12 54 22 PM" src="https://user-images.githubusercontent.com/20525304/183631735-bd053527-5573-49f0-a5e7-01378009f118.png">

**Comment by aabedraba** [comment]
Solved
