### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#607]
As a user when I try to access to a page that is not accessible 
I want to be presented with an error message 
So that I know why I may not be able to access and be able to navigate elsewhere.

**UX Design:**
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1382%3A33966

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/200
