### ISSUE TITLE
Dashboard V2: View CRD and Kusk extensions

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#618]
As I user I want to be able to view the CRD and kusk extensions for a given API.

**UX Design:**

- View Open API spec (read only) and swagger UI Docs
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1641%3A35303

- View CRD
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1641%3A35366

- View Extensions
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1680%3A36010

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/196
