### ISSUE TITLE
Dashboard: View Logging

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#626]
As a user I would like to see logging relevant to an API in the dashboard.

For MVP the user will see the logs for all APIs on a specific fleet.

**UX Design:**
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=2528%3A41243

**Prototype:**
https://www.figma.com/proto/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?page-id=2528%3A41243&node-id=2655%3A45834&viewport=-169%2C749%2C0.5&scaling=min-zoom&starting-point-node-id=2655%3A45834

**Comment by crjones** [comment]
As MVP logging can be implemented by fleet and exposed through the dashboard.

**Comment by jasmingacic** [comment]
As a solution we should have a web socket on the API server which will stream logs from the selected envoyfleet. 
The UI should then be able to filter routes by APIs that are deployed in the selected fleet

@donnalux do we need any additional information for this?

**Comment by donnalux** [comment]
@jasmingacic No, I have enough now to design with.

**Comment by mortada-codes** [comment]
Check sub tasks in the pr description

 https://github.com/kubeshop/kusk-gateway-dashboard/pull/347
