### ISSUE TITLE
Dashboard: Import or upload an Open API file

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#643]
As a user I would like to be able to upload my Open API file so that it is easier, faster and there is less chance of making a mistake by copying and pasting text. 

Upload file by drag and drop or selecting.

**UX Design:**

https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1894%3A37635

**Comment by mortada-codes** [comment]
blocked by https://github.com/kubeshop/kusk-gateway/issues/678

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/225
