### ISSUE TITLE
CLI: Report errors to telemetry

### ISSUE THREAD

**Issue by kylehodgetts** [kubeshop/kusk-gateway#645]
**Describe the enhancement you'd like to see**
We want to start collecting telemetry on the types of errors that users encounter so we can adjust the output to produce better formatted and more intuitive error messages + suggestions on what to do when this error appears

**Additional context**
Add any other context about the enhancement here.

**Comment by mbana** [comment]
Closing as it's been merged into `main` in <https://github.com/kubeshop/kusk-gateway/pull/722>.
