### ISSUE TITLE
Dashboard: No search results

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#646]
As a user when I search for an item via filters or search bar I would like to know that my search criteria has returned no results if that is the case.

**UX Design**:
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1818%3A36387

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/211
