### ISSUE TITLE
Dashboard: Improve error/warning/validation messaging

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#648]
As a user I'd like to see meaningful error messaging with solutions if possible.

- User edits kusk API endpoint which affects pretty much everything
- create api from api/url
- update api settings 

**UX**
- Remove all exclamation marks from validation messaging e.g.
<img width="157" alt="image" src="https://user-images.githubusercontent.com/102221761/193236636-33ed57db-302c-476f-b40d-af578c2ce583.png">

- All required fields to show validation message "Required"
- API name
![Image](https://user-images.githubusercontent.com/102221761/193547664-4b02fd1d-0410-420c-85aa-6311d3a4d56b.png)

- Open API spec
![Image](https://user-images.githubusercontent.com/102221761/193549675-2caff4e5-070c-4e71-8a41-cdba0059211d.png)

- Incorectly formatted path
![Image](https://user-images.githubusercontent.com/102221761/193550461-51869243-2dae-48d0-9ca5-46fd03839d90.png)
![Image](https://user-images.githubusercontent.com/102221761/193547829-325b7f29-6c07-4413-9739-5f96adf9a1ef.png)

- 
![Image](https://user-images.githubusercontent.com/102221761/193550887-f5e05db5-939c-4d70-b148-0adcea063a98.png)

- When user edits API endpoint
![Image](https://user-images.githubusercontent.com/102221761/193548117-4a4a255f-51c7-451a-bb93-3681a8b9136e.png)

**Comment by jasmingacic** [comment]
@donnalux has this been completed?

**Comment by donnalux** [comment]
@jasmingacic No, myself and @mortada-codes need to get list of errors.
