### ISSUE TITLE
GET /apis parameters don't work

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#663]
**Describe the bug**
cannot filter apis by namespace or fleetnamespace
**To Reproduce**
1. Run /apis with parameters 
2. See wrong results 

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/20525304/187690142-5f230086-558b-45e6-a724-f6e41f56d783.mp4

**Desktop (please complete the following information):**
 - Kubernetes version: 1.24
 - Kube Gateway Version : 1.1.6

**Comment by kylehodgetts** [comment]
If you're querying by fleetnamespace, you also need to provide the fleetname. However, you only need to provide the namespace if your querying by namespace @mortada-codes

**Comment by jasmingacic** [comment]
@mortada-codes can you confirm the above? 

Close the issue if it is no longer applicable
