### ISSUE TITLE
Cannot delete a deployed api 

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#665]
**Describe the bug**
when hitting /apis/namespace/apiname DELETE response with 500 with a clear error
**To Reproduce**
1. Run /apis/namespace/apiname DELETE
2. See error 500

**Expected behavior**
Delete the deployed api
**Screenshots**

https://user-images.githubusercontent.com/20525304/187697385-a3447ff2-1dbe-4455-86b4-d1582271d443.mp4

**Desktop (please complete the following information):**
 - Kubernetes version 1.124
 - Kube Gateway Version 1.1.6

**Comment by jasmingacic** [comment]
This seems to be working 
```
# curl -v --request DELETE 'http://localhost:8080/apis/default/ip-geolocation-api-888'
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> DELETE /apis/default/ip-geolocation-api-888 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Date: Thu, 01 Sep 2022 14:48:17 GMT
< Content-Length: 5
< 
null
* Connection #0 to host localhost left intact

```

I'm closing this for now
