### ISSUE TITLE
CLI: Move kusk api generate to kusk generate

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#667]
While the organization under `api` seems logical. We currently have only one command there and others were placed at a root level (ie. `kusk mock`). Being that we are an API developer tool, lets put all commands that would go under `api` at the root and use parents for non API related tasks. 

So `kusk api generate` becomes `kusk generate`

For good practice, let's keep `kusk api generate` for a release and mark it as deprecated in the help. I would normally say show a deprecated message on usage but that would defeat the purpose as it would be a breaking change since we pipe the output.

**Comment by mbana** [comment]
Marking as completed as <https://github.com/kubeshop/kusk-gateway/pull/730> change was merged into `main`.
