### ISSUE TITLE
CLI Help: Add Getting Started examples to kusk help

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#669]
**UX Design:**

- Please color code all help sections as per new style, see how Testkube got this working: https://github.com/kubeshop/testkube/pull/2215

- list commands alphabetically
- ensure Docs & Support links are as in visuals
 
**Help - Short Version**
https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=154%3A350

**Mock Help - Long Version**
https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=154%3A430

**Generate Help - Long Version**
https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=178%3A943

**Comment by aabedraba** [comment]
Duplicate
