### ISSUE TITLE
CLI Help: Add Getting Started to end of kusk install

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#670]
After installing kusk in a cluster provide some helpful examples of next actions.

For example:

```
💡  Access the dashboard by using the following command:
👉  kusk dashboard

💡  Deploy your first API:
👉  kusk api generate -i <URL to Todo example> | kubectl apply -f -

💡  Access Help and useful examples to get you started:
👉  kusk --help

```

**UX Design:**

https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=142%3A963

**Comment by jasmingacic** [comment]
![Image](https://user-images.githubusercontent.com/8327751/192782397-b8f67769-9f52-48f6-ac20-c1b301264d71.png)

**Comment by aabedraba** [comment]
Just missing help messages when an error occurs 

![image](https://user-images.githubusercontent.com/27779735/193238612-8aab111a-0e24-4175-ae62-0aa02cbe6362.png)
