### ISSUE TITLE
CLI: Move install and upgrade under a parent of cluster

### ISSUE THREAD

**Issue by crjones** [kubeshop/kusk-gateway#671]
Move cluster commands under the parent `cluster`

So `kusk install` becomes `kusk cluster install`

For good practice, let's keep `kusk install` for a release and mark it as deprecated in the help. Also, show a deprecated message on usage.

**Comment by jasmingacic** [comment]
As we already decided to move `kusk api generate` to root level `kusk generate` 
For sake of consistency I would leave install at the root level too

**Comment by aabedraba** [comment]
@crjones let's discuss this in planning
