### ISSUE TITLE
POST /apis can accept urls and files 

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#678]
**Is your feature request related to a problem? Please describe.**
Give the users ability to deploy a new api by providing and openapi file or a url 

**Describe the solution you'd like**
![Screen Shot 2022-09-02 at 11 17 11 AM](https://user-images.githubusercontent.com/20525304/188107975-e07f7e87-feb6-4785-a94d-62ae0560a8f3.png)

**Comment by jasmingacic** [comment]
We can do that on the server side too. Shouldn't you be getting the content of the file in the UI?

**Comment by mortada-codes** [comment]
Agree for the file content. can we accept a url?

**Comment by jasmingacic** [comment]
We don't accept URLs. I think you should do it on the client side and validate the content before passing it to  the server

**Comment by donnalux** [comment]
Don't we have the option to point to a local file or a url in the CLI?

**Comment by mortada-codes** [comment]
the only concern with the url, is the cors
