### ISSUE TITLE
Disable OAuth for a specific path

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#680]
**Describe the bug**
When trying to signout using OAuth, the application does not signout. 

**To Reproduce**

Use the following OpenAPI configuration (note that Envoy is deployed in `kusk-system`):

`oauth-kusk.yaml`
```yaml
apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: auth-oauth2-oauth0-authorization-code-grant
  namespace: default
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  spec: |
    openapi: 3.0.0
    info:
      title: auth-oauth2-oauth0-authorization-code-grant
      description: auth-oauth2-oauth0-authorization-code-grant
      version: '0.1.0'
    schemes:
    - http
    - https
    x-kusk:
      upstream:
        service:
          name: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
          namespace: default
          port: 80
      auth:
        scheme: oauth2
        oauth2:
          token_endpoint: https://aabedraba.eu.auth0.com/oauth/token
          authorization_endpoint: https://aabedraba.eu.auth0.com/authorize
          credentials:
            client_id: vEZT09ShdFO4iHCu0HCmMqy71pB2orzQ
            client_secret: CoDszWd0M3A2z4ITi8yV4SCfAixulnMAc07C6Dm4Fb1ZMqy-mrcEd_zcjDH77aTJ
          redirect_uri: /oauth2/callback
          redirect_path_matcher: /oauth2/callback
          signout_path: /oauth2/signout
          forward_bearer_token: true
          auth_scopes:
            - openid
    paths:
      "/":
        get:
          description: Returns GET data.
          operationId: "/get"
          responses: {}
      "/uuid":
        get:
          description: Returns UUID4.
          operationId: "/uuid"
          responses: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
  namespace: default
  labels:
    app: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
spec:
  selector:
    matchLabels:
      app: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
    spec:
      containers:
        - name: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
          image: docker.io/mccutchen/go-httpbin:v2.4.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
  namespace: default
  labels:
    app: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
spec:
  selector:
    app: auth-oauth2-oauth0-authorization-code-grant-go-httpbin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
```
Now apply it 

```sh
kubectl apply -f oauth-kusk.yaml
```

2- Configure ConfigMap and restart Envoy as describe in the docs here: https://docs.kusk.io/guides/oauth2#envoy-fleet

3- Port-forward to the default EnvoyFleet on port `8080` (important, as my Auth0, the one in the example, is configured for that port) and try through the browser to access `http://localhost:8080/`, which will take you through Auth0 signing flow.

4- Once you're authenticated and you can see the content of  `http://localhost:8080`, try to access through the browser the following url for logging out `http://localhost:8080/oauth2/signout` 

5- You will see that you were not signed out, and the OAuth cookies are not erased. 

**Expected behavior**
Calling `/oauth2/signout/` should signout and take me to the signing page (Auth0's signing)

**Version**
```sh
$ kusk version
kusk version 1.2.0
https://github.com/kubeshop/kusk/releases/tag/v1.2.0
$ helm ls -n kusk-system
NAME                            	NAMESPACE  	REVISION	UPDATED                              	STATUS  	CHART                        	APP VERSION
kusk-gateway                    	kusk-system	1       	2022-09-02 12:10:56.481033 +0200 CEST	deployed	kusk-gateway-0.0.36          	v1.2.0
kusk-gateway-api                	kusk-system	1       	2022-09-02 12:15:06.354311 +0200 CEST	deployed	kusk-gateway-api-0.1.14      	v1.1.4
kusk-gateway-dashboard          	kusk-system	1       	2022-09-02 12:16:36.085425 +0200 CEST	deployed	kusk-gateway-dashboard-0.1.11	v1.1.0-stable
kusk-gateway-envoy-fleet        	kusk-system	1       	2022-09-02 12:12:26.362519 +0200 CEST	deployed	kusk-gateway-envoyfleet-0.0.5	v0.0.0
kusk-gateway-private-envoy-fleet	kusk-system	1       	2022-09-02 12:13:45.800318 +0200 CEST	deployed	kusk-gateway-envoyfleet-0.0.5	v0.0.0
```

**Comment by mbana** [comment]
I don't think the signout path is working in Envoy itself.

I've tried this, <https://github.com/veehaitch/envoy-oauth2-filter-google>, simple example with some slight modifications that I can share. Ping me and I'll make the repository public or something. Basically just put in the oauth0 credentials in there.

Simply put, after going to <http://localhost:8080/oauth2/signout> a redirect to `/` happens which then causes it to acquire a token again. The behaviour is a bit puzzling as the cookies are not cleared out either when I call the `/oauth2/sighout` path from the command line with the cookie.

I've raised an issue in this, <https://github.com/veehaitch/envoy-oauth2-filter-google/issues/2>, example repository asking the author to also check if `signout_path` does indeed work or not.

I'm marking the issue as blocked until we receive feedback.

**Comment by aabedraba** [comment]
@mbana testing from the CLI the `/oauth2/signout` I see that it generates correctly the `set-cookie: cookieName=deleted` which is the way that the browser knows that the server wants the cookies to be deleted. But for some reason, the browser disregards those cookies... 

```sh 
http -v http://localhost:8080/oauth2/signout "Cookie:LONG_COOKIE"
GET /oauth2/signout HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Cookie: LONG_COOKIE
Host: localhost:8080
User-Agent: HTTPie/3.2.1



HTTP/1.1 302 Found
content-length: 0
date: Mon, 05 Sep 2022 19:39:07 GMT
location: http://localhost:8080/
server: envoy
set-cookie: OauthHMAC=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
set-cookie: BearerToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
set-cookie: IdToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
set-cookie: RefreshToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
```

**Comment by mbana** [comment]
> @mbana testing from the CLI the `/oauth2/signout` I see that it generates correctly the `set-cookie: cookieName=deleted` which is the way that the browser knows that the server wants the cookies to be deleted. But for some reason, the browser disregards those cookies...
> 
> ```shell
> http -v http://localhost:8080/oauth2/signout "Cookie:LONG_COOKIE"
> GET /oauth2/signout HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Cookie: LONG_COOKIE
> Host: localhost:8080
> User-Agent: HTTPie/3.2.1
> 
> 
> 
> HTTP/1.1 302 Found
> content-length: 0
> date: Mon, 05 Sep 2022 19:39:07 GMT
> location: http://localhost:8080/
> server: envoy
> set-cookie: OauthHMAC=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
> set-cookie: BearerToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
> set-cookie: IdToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
> set-cookie: RefreshToken=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT
> ```

So it deletes the cookies as I mentioned but then it does the redirect, (`HTTP/1.1 302 Found`), to `/`.

I think we should either try to get signout working on the basic example from <https://github.com/veehaitch/envoy-oauth2-filter-google> or wait until the issue I raised gets a response from the author.

**Comment by aabedraba** [comment]
@mbana I believe we are functioning correctly. 

From Auth0's documentation: 

> Logout issues
> Make the logout redirect URL an anonymous page (not protected by login) so that redirects to the logout redirect URL do not immediately trigger a login, which may confuse users.

So, because the OAuth2 rule is applied globally, redirecting to `/` triggers another login. This time it does not ask for a password because we're already logged in with Google! 😫 

I think the solution is to have a `path-after-logout` (for lack of a better name) option in our extension, and then we set Envoy to not protect that path with the auth rule.

**Comment by aabedraba** [comment]
We're going to implicitly (from a user's perspective) disable OAuth on the root path.

**Comment by mbana** [comment]
Just leaving a note here of what I stumbled across.

Please note: [`[Oauth] Option to customize sign-out redirect #18983
`](https://github.com/envoyproxy/envoy/issues/18983).

Itsio allows you to control the route that the user will redirected to upon logout, see: <https://github.com/istio-ecosystem/authservice/blob/5d3a9023bfea111d98a091f9a6e67e04c1646086/test/filters/oidc/oidc_filter_test.cc#L938>.
