### ISSUE TITLE
CLI: Implement color theme

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#690]
To ensure the kusk theme will  be legible regardless of users terminal theme use foreground color as selected text.
See:
https://gookit.github.io/color/#/?id=cli-color

Implement theme as per Kusk CLI design:
https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=0%3A1

**Comment by jasmingacic** [comment]
Deploy:
![image](https://user-images.githubusercontent.com/8327751/189776215-a6fe6131-dd66-46bc-8852-06a9e1b9566a.png)
Deploy + watch
![image](https://user-images.githubusercontent.com/8327751/189776256-a49c3dd0-421e-4f30-8481-fb2b131faeb5.png)
