### ISSUE TITLE
Mark `kusk-gateway-envoy-fleet` as Default on installation and upgrade

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#707]

**Comment by aabedraba** [comment]
Re-opening just so we can discuss more the upgrade flow

**Comment by jasmingacic** [comment]
I believe #731  should deal with this

**Comment by kylehodgetts** [comment]
@jasmingacic I dont see how switching from helm to manifests will solve this. When you upgrade it will use the latest chart which will have the default setting

**Comment by jasmingacic** [comment]
A webhook should deal with this for the users. Less than ideal

Also having default envoy fleet doesn't really do much. So far it is used in generate and deploy to pick the default one and if not available we prompt users to make one fleet default.

**Comment by aabedraba** [comment]
> Also having default envoy fleet doesn't really do much.

I think it's not about the current functionality, but the one to come 🤔 

Also, currently we're not using `default` field in the `generate` command, we've hardcoded it: https://github.com/kubeshop/kusk-gateway/blob/main/cmd/kusk/cmd/generate.go#L289-L295

**Comment by aabedraba** [comment]
@jasmingacic just pending test by @jasmingacic

**Comment by jasmingacic** [comment]
After running 
```
./kusk cluster install 
✅ installing kusk...
✅ installing Envoyfleet...
✅ installing API Server...
✅ installing Dashboard...

🎉 installation complete

💡 Access the dashboard by using the following command
👉 kusk dashboard

💡 Deploy your first API
👉 kusk deploy -i <path or url to your api definition>

💡 Access Help and useful examples to help get you started
👉 kusk --help
```
```
# kubectl get envoyfleet -A -o json | jq .items[].spec.default
true
null
```

**Comment by jasmingacic** [comment]
I manually change the default fleet 
```
# kubectl get envoyfleet -A -o json | jq .items[].spec.default
null
null
```
And then ran
```
# ./kusk cluster upgrade
✅ Checking if kusk is already installed...
✅ kusk is already installed. Upgrading...
✅ kusk upgraded
✅ kusk API server is already installed. Upgrading...
✅ API Server installed
✅ Envoy Fleets upgraded
✅ kusk Dashboard is already installed. Upgrading...
✅ Dashboard upgraded
✅ Envoy Fleets upgraded
```
and it added default envoyfleet:
```
 kubectl get envoyfleet -A -o json | jq .items[].spec.default
true
null
```
