### ISSUE TITLE
Add a message in the CLI to update Kusk CLI

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#721]
```bash
$ kusk deploy -i openapi.yaml
New version of the Kusk CLI is released: use xxxx to upgrade the CLI

API deployed
```

**Comment by crjones** [comment]
Be sure not to add this message to any command that generates output that is expected to be consumed by another process.

**Comment by aabedraba** [comment]
@donnalux UX for this when you can

**Comment by aabedraba** [comment]
For reference, this is how github does it: [cli/cli@bde64b3/cmd/gh/main.go#L263-L278](https://github.com/cli/cli/blob/bde64b31919f191c7523b4a3bcc4f56e69e30f87/cmd/gh/main.go#L263-L278)

This is how it looks like:

[image
](https://user-images.githubusercontent.com/27779735/189222837-36dfb6ee-2024-4d67-8a59-7db050553679.png)

I also like their color library tbh: [mgutz/ansi](https://github.com/mgutz/ansi)

Another example from npm.. but this feels a bit too intrusive maybe? 

![image](https://user-images.githubusercontent.com/27779735/189230688-f3f544e8-6702-4540-aa78-e3f02910274a.png)

**Comment by donnalux** [comment]
@jasmingacic This issue shouldn't have been closed with label needs ux
https://www.figma.com/file/EkNk9tMEoAgYrwGP7N1dPm/Kusk-CLI?node-id=225%3A347

What's been done has a spelling mistake (your) so if you are fixing can you take a look at the figma, thanks.
