### ISSUE TITLE
Dashboard: User cannot edit name or namespace of API/Static route

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#736]
After the creation of an API or static route, the user should be able to view the name and namespace but not edit same.

UX design:
Namespace is disable and non editable.
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=1324%3A32512

**Comment by jasmingacic** [comment]
@donnalux I believe we clarified this on the touch base earlier today. Would you close it if you agree?

**Comment by aabedraba** [comment]
@mortada-codes if this is done, could you pls close it?

**Comment by aabedraba** [comment]
Missing some testing and we can go on
