### ISSUE TITLE
Dashboard: Handle when APIs target same path 

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#750]
Linked to:
https://github.com/kubeshop/kusk-gateway/issues/737

**UX Design:**

https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=2746%3A41440

**Comment by jasmingacic** [comment]
https://github.com/kubeshop/kusk-gateway/pull/753 will take care of this

**Comment by donnalux** [comment]
@jasmingacic this needs to be handled on the Dashboard UI also

**Comment by aabedraba** [comment]
Backend is done. We'd need to know if @mortada-codes can have it before we release 1.3.0

**Comment by aabedraba** [comment]
@donnalux working on UX.

**Comment by aabedraba** [comment]
Just return the API error for now, let's not customize the error message at the moment.

**Comment by aabedraba** [comment]
@mortada-codes what is blocked on this?

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/kusk-gateway-dashboard/pull/322
