### ISSUE TITLE
kusk + istio

### ISSUE THREAD

**Issue by neeltom92** [kubeshop/kusk-gateway#751]
* i use istio service mesh for ingress only , is it possible to integrate kusk with istio
* are API rate limiting features there for kusk

**Comment by jasmingacic** [comment]
@neeltom92 thanks for reaching out. 

API rate limiting is configurable through kusk extensions. Check this link for details https://docs.kusk.io/guides/rate-limit

We are not compatible with Istio at the moment we are directly configuring vanilla Envoy proxy. In your case where you are using istio for ingress only you could simply replace Istio with Kusk. If you are interested how to do it please book a demo [here](https://calendly.com/kusk_gateway/demo) and we can guide you through the process and gladly answer any of your questions.

**Comment by neeltom92** [comment]
thanks

**Comment by neeltom92** [comment]
thanks @jasmingacic and @aabedraba 
let me clarify my exact requirement.

I have set up Istio for ingress public traffic, using the AWS ALB.
to give you a further idea on this, let me share the link based on which my set up is done : https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/

if it's TLDR; let me share a snapshot from the link so its clarified.
![image](https://user-images.githubusercontent.com/26869835/191807872-629004f3-b0fb-4694-ab85-c84a83d28b10.png)

now coming to my exact requirement, as you can see I use Istio just for ingress traffic to my application.
I would need  below 2 features for my API GW:
1. rate limiting
2. traffic mirroring.
I agree that both can be achieved with service Mesh like Istio, but the set up at least for me feels complex.

so if I can deploy kusk as proxy GW that sits before my application and does the tasks mentioned.
at least for rate limiting what I did was to create a temporary application that sites before my actual rest API app and do the rate-limiting, sharing for reference : https://github.com/neeltom92/ginger

BTW, sorry for asking such questions and really appreciate you both for helping with answering the question previously.

**Comment by aabedraba** [comment]
Hey @neeltom92 
good stuff!! Please never be sorry for asking, this is the right stuff we're looking for! 

I'll try to run this setup today or tomorrow and come back to you, just to ensure that everything's working (certificates included). 

Initially, it seems that Istio can be replaced with Kusk because in the diagram Isitio is used as a gateway. A feature that we don't have yet is traffic mirroring, but Envoy (the proxy we're based on) supports it, so it'd be a matter of creating the right extensions in OpenAPI. If you think this is crucial for you, we are more than happy to work on it!

**Comment by neeltom92** [comment]
thanks @aabedraba its not critical it's fine for me , appreciate the help, but I would really appreciate your blog on implementing Kusk + Istio together like below, Kong + Istio : https://konghq.com/blog/istio-gateway.
also further would help if there would be a blog on ALB + EKS  + Kusk coz for running Production workloads in EKS, this is the combinations most Devops/SRE's like me prefer :)
