### ISSUE TITLE
StaticRoute is missing policies

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#763]
Most of the new policies do not work with StaticRoute

**Comment by aabedraba** [comment]
`rate-limit`, `cache`, etc are also not supported. I think we just stopped updating the validator for a while. 

We need to make all extensions that are available to API work with StaticRoute as well.

**Comment by donnalux** [comment]
@aabedraba right now on the dashboard, extensions for static routes are only applied at a path level. Should they be applied at an operational level also?
