### ISSUE TITLE
Generate returns error and generates the manifest

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#770]
From Discord user @gerardorn 

```
However I found a weird behavior:

As I'm starting to work using a design first approach, I have been creating endpoints with no kusk integration yet and when running the kusk api generate command, sometimes it complains about this but eventualy generates the spec (I haven't checked if the spec makes sense or not)

here's a screenshot were I ran consecutive times the generation command 
```
![image](https://user-images.githubusercontent.com/8327751/192164552-73319fcf-92f1-4a04-a80d-18b70efb68ea.png)

I requested the OpenAPI definition he used so we can replicate it. 

By the first look of it I'd say there is a mistake in the spec the user used but generate should be failing if validate does not pass.

**Comment by gerardorn** [comment]
hey team, @jasmingacic 👋🏼 

Here's the link to the raw openapi spec used

https://gitlab.com/evolucion-digital/code/containerp/api/-/raw/main/containerp.openapi.yaml

Promise I won't move it again 😰

**Comment by jasmingacic** [comment]
Closing this as non issue
