### ISSUE TITLE
CLI Install: Provide APT package and possibly an apt repository

### ISSUE THREAD

**Issue by mbana** [kubeshop/kusk-gateway#776]
**Describe the enhancement you'd like to see**

We should provide a way for users on Debian-like systems to install `kusk` via [`apt`](https://en.wikipedia.org/wiki/APT_(software)).

We should additionally consider adding a repository for `kusk` so that users can get updates automatically.

**Additional context**

Easier for users to install `kusk` and potentially update it.

**Comment by crjones** [comment]
let's use kusk-dev@kubeshop.io

**Comment by kylehodgetts** [comment]
Update: APT repo server is live and can accept packages and packages can be installed from it. All that's left to do is to properly mount a large non-boot disk via the OS to store the packages and create backups of
