### ISSUE TITLE
CLI Install: Provide snap package 

### ISSUE THREAD

**Issue by mbana** [kubeshop/kusk-gateway#777]
**Describe the enhancement you'd like to see**

We should provide a way for users using [`snapd`/`snap`](https://snapcraft.io/) to install `kusk` via the [Snap Store](https://snapcraft.io/store).

**Additional context**

Easier for users to install `kusk` and potentially update it.

**Comment by aabedraba** [comment]
I believe that `snap` is not a relevant packaging as it has heavily declined in popularity due to its dependance on Canonical and the "unwelcome" way of installation.

**Comment by jasmingacic** [comment]
we decided we wouldn't do snap packages.
