### ISSUE TITLE
CLI Install: Provide choco package

### ISSUE THREAD

**Issue by mbana** [kubeshop/kusk-gateway#779]
**Describe the enhancement you'd like to see**

We should provide a way for users using Windows to install `kusk.

**Additional context**

Easier for users to install `kusk` and potentially update it.

**Comment by aabedraba** [comment]
Ole:
the official choco repo has a huge lag for releasing new artifacts (weeks...) - so that's why we have our own server...

you could use it for kusk also

**Comment by aabedraba** [comment]
Currently just focusing on APT
