### ISSUE TITLE
Make envoy's text template fixed - envoy.access_loggers.stdout

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kusk-gateway#784]
Currently we are allowing users to change log output format by allowing them to change this value:
https://github.com/kubeshop/kusk-gateway/blob/main/config/samples/gateway_v1_envoyfleet.yaml#L80-L81

In order to enable log browsing in the Dashboard we should make this unchangeable so we can always hook into envoy's logs and parse them

**Comment by mbana** [comment]
Just leaving my thoughts so I don't forget.

Perhaps we should Itsio's default access log format as it's sensible:

<https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format>

For more details about access logs in Envoy see:

<https://www.envoyproxy.io/docs/envoy/v1.23.1/configuration/observability/access_log/usage>
