### ISSUE TITLE
Add authorization integration documentation 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#787]
Add Cloudentity integration docs

@jasmingacic to share the docs about the integration

**Comment by jasmingacic** [comment]
https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/588709893/WIP+Getting+started+with+Kusk+gateway+and+Cloudentity

**Comment by mbana** [comment]
Part of the work is done in the merged PR: <https://github.com/kubeshop/kusk-gateway/pull/796>.

Feel free to close @aabedraba, if you think that's fine.
