### ISSUE TITLE
Dashboard: CORS Max age field appears to have default of 60

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#831]
The CORS Max Age field has a default value of 60 but is not represented in API spec.
![image](https://user-images.githubusercontent.com/102221761/194054156-84f07667-cd72-43b2-89da-aff30610786a.png)

Expected behavior:
CORS Max Age field should be empty.

**Comment by mortada-codes** [comment]
should we use the default? 
![Screen Shot 2022-10-05 at 2 14 13 PM](https://user-images.githubusercontent.com/20525304/194057941-78ea43bf-a33b-47e5-8133-1756da82c240.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests
