### ISSUE TITLE
Add `kusk validate` command

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#859]
As a user I just want to run a command to check if my x-kusk policies are configured correctly, but I don't want to apply it to the cluster just yet. 

Can we have a command `kusk validate` that uses the validation that we already run with `kusk deploy`?

**Comment by olensmar** [comment]
perhaps `kusk validate` would be better - linting is something we could support separately!?

**Comment by jasmingacic** [comment]
Validate will lint as well. But let's focus first on validation
