### ISSUE TITLE
Dashboard: UX Debt - Policies

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#926]
UX Feedback from #426  :

- Root row is being incorrectly included in filter results 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/102221761/197154836-8742435a-513c-4d8a-b165-8897bb953d6b.png">
- Can we enlarge expand target area so it's easier for user to select control
<img width="249" alt="image" src="https://user-images.githubusercontent.com/102221761/197155903-6e608a7b-5218-46f4-8b78-df54bd3cb834.png">
- check hover styling for hide/enable menu - sizing, hover styling/behaviour and icon color.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/102221761/197160950-ab3fa945-0fa4-47d9-9db0-bb179807262a.png">
- menu should height should reach to bottom of screen
<img width="86" alt="image" src="https://user-images.githubusercontent.com/102221761/197161231-2743d79b-c1f7-48a6-93c5-73a00e084970.png">
- Form sub headers (CORS) should be font weight regular/400
- Styling of a disabled path or operation should match that of figma design
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3208%3A55542

- input label is incorrect style
<img width="612" alt="image" src="https://user-images.githubusercontent.com/102221761/197753475-c807ec48-cc24-4d7b-848f-08f3fe621f92.png">

**Comment by mortada-codes** [comment]
addressed: https://github.com/kubeshop/kusk-gateway-dashboard/pull/346

**Comment by donnalux** [comment]
@mortada-codes there's still a couple of things here - the CORS sub headers, disabled path/operation styling and the menu styling. We can have a chat about it.
