### ISSUE TITLE
Admission webhook validation for multiple configs

### ISSUE THREAD

**Issue by Tarick** [kubeshop/kusk-gateway#95]
When we supply crd (either StaticRoute or API) we need to validate new config against already present ones in case conflicting routes exist.
This means to get all configs in the cluster, create Envoy config from them and then apply new CRD config and check for errors.
The problem here is that Admission webhook implementation can't get client.Client to access Kubernetes, so we need to inject that somehow.

**Comment by aabedraba** [comment]
This is already a supported feature.
