### ISSUE TITLE
Dashboard: Disable a path/operation

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#958]
As a user I would like to have a visual indicator that a path or operation of an API has been disabled.

**UX Design:**

https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3208%3A55542

**Comment by aabedraba** [comment]
Blocked on https://github.com/kubeshop/kusk-gateway/issues/1000
