### ISSUE TITLE
Dashboard: 42Crunch Integration

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#974]
As a user I would like to be able to detect security vulnerabilities in my API.

**UX Design:**

Add policy
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3740%3A45114&t=q1QoyQzWlDExegJk-4

View 42Crunch link and details
Option 1 (my perference)
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3811%3A44575&t=q1QoyQzWlDExegJk-4

Option 2 
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3811%3A44634&t=q1QoyQzWlDExegJk-4

**Comment by jasmingacic** [comment]
![image](https://user-images.githubusercontent.com/8327751/202165770-24fb025e-9d2b-4d46-97c7-5550ef169a40.png)

**Comment by jasmingacic** [comment]
Implementation details are still unknown while we are waiting on their documentation. Initial version implementation proposal is here (WIP) https://kubeshop.atlassian.net/l/cp/RsKCdfho

**Comment by aabedraba** [comment]
@mortada-codes I believe this is not done

**Comment by aabedraba** [comment]
blocked on #998
