### ISSUE TITLE
Dashboard: Add JWT as a policy

### ISSUE THREAD

**Issue by donnalux** [kubeshop/kusk-gateway#982]
**UX Design:**
https://www.figma.com/file/wecNPLnwPgaQiZaXDWolSa/Kusk-Gateway-Dashboard?node-id=3717%3A42899&t=RaVSAFXWZWsPRZl9-4

**Comment by aabedraba** [comment]
Kusk API has a bug. https://github.com/kubeshop/kusk-gateway/issues/1000
